### ISSUE TITLE
TS.ALTER Command missing

### ISSUE THREAD

**Issue by semirix** [tompro/redis_ts#10]
I noticed there isn't a `TS.ALTER` command present in neither sync nor async API. I believe the signature is exactly the same as `TS.CREATE`. Could this be added in?

**Comment by semirix** [comment]
Okay, so it appears I've made a mistake. There is a command in the sync API but not the async API according to the docs.

**Comment by tompro** [comment]
Thanks for the report. Issue is fixed in v0.4.1.

**Comment by semirix** [comment]
Thanks for the speedy fix! Much appreciated :smile:
