### ISSUE TITLE
Weird error about DUPLICATE_POLICY

### ISSUE THREAD

**Issue by kairosdojo** [tompro/redis_ts#12]
# Environment
* **OS**  : 5.18.19-3-MANJARO
* **rustc**: 1.60.0 (7737e0b5c 2022-04-04)

**Redis setup**
* **Redis version         :** 6.2.4,
* **Redis TimeSeries  :** 999999, (git_sha=7601fc8126e47a90...)

**Crates**
* `redis = { version = "0.21.5", features = ["tokio-comp"] }`
* `redis_ts = "0.4.1"`
* `tokio-test = "0.4.2"`

# The Issue
When I try an **upsert** with  `ts_add_create()` [like explained here](https://docs.rs/redis_ts/latest/redis_ts/#tsadd):

```rust
let redists_options = TsOptions::default().duplicate_policy(TsDuplicatePolicy::Last);
let _:u64 = conn.ts_add_create(format!("MARKET:{}:{}", t, "open"), tms, qv.open as f32, redists_options.clone()).unwrap();
```

I receive the error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: An error was signalled by the server: TSDB: Error at upsert, update is not supported when DUPLICATE_POLICY is set to BLOCK mode', src/main.rs:94:126
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

In reality, **running redis-cli monitor**, I can clearly see that the upsert took place correctly!

![Screenshot_2022-10-21_10-12-56](https://user-images.githubusercontent.com/22766463/197150935-5e643808-035f-4aa9-b24c-56f6270882af.png)

How is that possible? Where does this error come from?

# A (bad) fix

I followed [these instructions](https://redis.io/docs/stack/timeseries/configuration/) to set `DUPLICATE_POLICY LAST` globally in my redis config file, whilst loading the module:

![Screenshot_2022-10-21_10-24-27](https://user-images.githubusercontent.com/22766463/197151058-3cb65f97-f871-44b7-a227-e6b55f54ab45.png)

In this way it indeed works...

![Screenshot_2022-10-21_10-27-22](https://user-images.githubusercontent.com/22766463/197154079-2edcabd1-4342-41cd-a52b-365b5a078696.png)

... and no errors are returned. 

Of course, though, this is not intended behavior. 

## Addendum

Maybe it can help knowing that doing a

```python
rts.add(key, tms, data, duplicate_policy='last')
```

using this [python client for redists](https://github.com/RedisTimeSeries/redistimeseries-py#usage-example) works without the need of having a global duplicate policy.

Thank you!

**Comment by tompro** [comment]
Hi @kairosdojo, thank you for reporting this. I am sorry to tell you that I could not reproduce your issue though. I have added a test case that is checking your workflow. All tests are run against a fresh Redis instance (docker.io/redislabs/redismod) with no global configurations whatsoever. You can find the tests here:

[Test upsert with config](https://github.com/tompro/redis_ts/blob/59367c33c9d8320edbbf42c894061a12592a4de1/tests/test_commands.rs#L140) 

The error you are describing comes directly as a response from your Redis server. I can just guess here but I think you had some global setting active setting all ts to BLOCK or you created a ts configured with BLOCK. Keep in mind If a ts key is already set to BLOCK you get an error if you try to insert values older then the last one. Docs (https://redis.io/docs/stack/timeseries/configuration/):

`BLOCK - an error will occur for any out of order sample`

**Comment by kairosdojo** [comment]
Thank you!
